[workspace]
members = ["texas-holdem-common", "texas-holdem-server", "texas-holdem-client"]
# https://github.com/gfx-rs/wgpu/issues/2217
# https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
resolver = "2"